// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    // ignore: missing_enum_constant_in_switch
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
    }

    throw UnsupportedError(
      'DefaultFirebaseOptions are not supported for this platform.',
    );
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDe3AP5j_AGOx7CBccz15A9NLzIHojm6T0',
    appId: '1:517790856908:android:adf79e2f21a4503aedf469',
    messagingSenderId: '517790856908',
    projectId: 'kindergarten-2a1b9',
    storageBucket: 'kindergarten-2a1b9.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB8pD0JPhc-BjSrHXJfTRqItlXGB5GC_dE',
    appId: '1:517790856908:ios:610134b095eb947fedf469',
    messagingSenderId: '517790856908',
    projectId: 'kindergarten-2a1b9',
    storageBucket: 'kindergarten-2a1b9.appspot.com',
    iosClientId: '517790856908-ds0f4mn79ej9amg97j1t69134am20eoe.apps.googleusercontent.com',
    iosBundleId: 'com.phoenix.kindergarten',
  );
}
